name: Validate

on:
  push:
    branches:
      - main
  pull_request:
  #schedule:
  #  - cron: '0 12 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions: {}

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          persist-credentials: false

      - name: Validate configuration
        run: |
          npx --yes --package renovate -- \
            renovate-config-validator --strict config.json5
